name: Build and publish npm package

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test
        env:
          CI: true

      - name: Build
        run: bun run build

      - name: Publish to GitHub Packages
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
        run: bun publish --registry https://npm.pkg.github.com --access public

      - name: Publish to npmjs.com
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPMJS_AUTH_TOKEN }}
        run: bun publish --registry https://registry.npmjs.org --access public
